# Generated by Django 5.1.1 on 2024-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='promptBitmapAsBinary',
        ),
        migrations.AddField(
            model_name='prompt',
            name='promptHeight',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='promptImageData',
            field=models.CharField(default='string'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='promptWidth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
